# -*- coding: utf-8 -*-
"""canny_algorithm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/179BVwjGO5lseB0MYcmPAoWi3CJc5H_Po
"""

def canny(image, sigma=1.0):

  gaussian_image = gaussian_smoothing(image, sigma)
  gradient_magnitude, gradient_angle = calculate_gradients(gaussian_image)
  potential_edges = non_maximum_supression(gradient_magnitude, gradient_angle) 
  threshold = otsu_threshold(gradient_magnitude)   
  strong_edges, weak_edges = double_threshold(potential_edges, threshold) 
  edges = edge_hysteresis(strong_edges, weak_edges)

  return edges