# -*- coding: utf-8 -*-
"""double_threshold.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/179BVwjGO5lseB0MYcmPAoWi3CJc5H_Po
"""

def double_threshold(potential_edges, threshold):
  high_threshold = threshold
  low_threshold = threshold / 5
 
  strong_edges = np.zeros(potential_edges.shape)  
  weak_edges = np.zeros(potential_edges.shape)

  strong = 1 
  weak = 0.4
    
  strong_y, strong_x = np.where(potential_edges > high_threshold)
  weak_y, weak_x = np.where((potential_edges <= high_threshold) & (potential_edges >= low_threshold))
  
  strong_edges[strong_y, strong_x] = strong
  weak_edges[weak_y, weak_x] = weak  
    
  return strong_edges, weak_edges