# -*- coding: utf-8 -*-
"""calculate_gradients.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/179BVwjGO5lseB0MYcmPAoWi3CJc5H_Po
"""

def calculate_gradients(image):
  window_x = np.array([        # filtr Sobela
    [-1, 0, 1],
    [-2, 0, 2],
    [-1, 0, 1]                     
  ])
  window_y = window_x.T
  gradient_x = signal.correlate2d(image, window_x)
  gradient_y = signal.correlate2d(image, window_y)

  gradient_magnitude = np.sqrt(gradient_x**2 + gradient_y**2)     # intensywność krawedzi
  gradient_angle = np.arctan2(gradient_y, gradient_x)*180/np.pi      # kierunek krawedzi

  return gradient_magnitude, gradient_angle